export enum BoardActionTypes {
  GET_BOARDS_SUCCESS = 'GET_BOARDS_SUCCESS',
  ADD_BOARD_ACTION = 'ADD_BOARD_ACTION',
  DELETE_BOARD_ACTION = 'DELETE_BOARD_ACTION',
  EDIT_BOARD_ACTION = 'EDIT_BOARD_ACTION',
}
