export enum BoardActionTypes {
  FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS',
  ADD_BOARD_SUCCESS = 'ADD_BOARD_SUCCESS',
  ADD_BOARD_ERROR = 'ADD_BOARD_ERROR',
  DELETE_BOARD_SUCCESS = 'DELETE_BOARD_SUCCESS',
  DELETE_BOARD_ERROR = 'DELETE_BOARD_ERROR',
  EDIT_BOARD_SUCCESS = 'EDIT_BOARD_SUCCESS',
  EDIT_BOARD_ERROR = 'EDIT_BOARD_ERROR',
}
