export enum BoardActionTypes {
  FETCH_BOARDS_SUCCESS = 'FETCH_BOARDS_SUCCESS',
  ADD_BOARD_ACTION = 'ADD_BOARD_ACTION',
  DELETE_BOARD_ACTION = 'DELETE_BOARD_ACTION',
  EDIT_BOARD_ACTION = 'EDIT_BOARD_ACTION',
}
