export enum TodoColumnActionTypes {
  GET_TODO_COLUMNS_ACTION = 'GET_TODO_COLUMNS_ACTION',
  ADD_TODO_COLUMN_ACTION = 'ADD_TODO_COLUMN_ACTION',
  DELETE_TODO_COLUMN_ACTION = 'DELETE_TODO_COLUMN_ACTION',
  EDIT_TODO_COLUMN_TITLE_ACTION = 'EDIT_TODO_COLUMN_TITLE_ACTION',
}
