export enum TodoItemActionTypes {
  GET_TODO_ITEM_ACTION = 'GET_TODO_ITEM_ACTION',
  ADD_TODO_ITEM_ACTION = 'ADD_TODO_ITEM_ACTION',
  DELETE_TODO_ITEM_ACTION = 'DELETE_TODO_ITEM_ACTION',
  EDIT_TODO_ITEM_TITLE_ACTION = 'EDIT_TODO_ITEM_TITLE_ACTION',
}
