export enum UiActionTypes {
  LOADER_ON_ACTION = 'LOADER_ON_ACTION',
  LOADER_OFF_ACTION = 'LOADER_OFF_ACTION',
  OPEN_TOAST_ACTION = 'OPEN_TOAST_ACTION',
  CLOSE_TOAST_ACTION = 'CLOSE_TOAST_ACTION',
}
