export enum UiActionTypes {
  LOGIN_UI_SUCCESS = 'LOGIN_UI_SUCCESS',
  LOGIN_UI_ERROR = 'LOGIN_UI_ERROR',
  CLOSE_TOAST = 'CLOSE_TOAST',
  REGISTER_UI_SUCCESS = 'REGISTER_UI_SUCCESS',
  REGISTER_UI_ERROR = 'REGISTER_UI_ERROR',
}
