export enum UiActionTypes {
  LOADER_ON = 'LOADER_ON',
  LOADER_OFF = 'LOADER_OFF',
  LOGIN_TOAST_SUCCESS = 'LOGIN_TOAST_SUCCESS',
  LOGIN_TOAST_ERROR = 'LOGIN_TOAST_ERROR',
  REGISTER_TOAST_SUCCESS = 'REGISTER_TOAST_SUCCESS',
  REGISTER_TOAST_ERROR = 'REGISTER_TOAST_ERROR',
  CLOSE_TOAST = 'CLOSE_TOAST',
}
